# NumPy Getting Started Guide

NumPy, which stands for Numerical Python, is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, as well as mathematical functions for operations with these objects. It is also the basis of the Pandas library.

## Installation

To install NumPy, you can use pip, which is Python's package manager.

```python
pip install numpy
```

## Arrays

An array is a data structure that stores values of the same type. In Python, this is a big advantage because it saves space and allows for more efficient operations. Let's create an array.

In [1]:
import numpy as np

array = np.array([1,2,3,4,5])

print(array)

[1 2 3 4 5]


## Get to know an array - Index and Slice:

In [2]:
print(array[0]) # accessing value with index number

1


In [6]:
print(f'Initial array: {array}')
print(array[1:4]) # acessing interval of values (includes index 1; excludes index 4)

Initial array: [1 2 3 4 5]
[2 3 4]


In [7]:
print(f'Initial array: {array}')
print(array[0:-1]) # acessing interval of values (includes index 0; excludes index -1)

Initial array: [1 2 3 4 5]
[1 2 3 4]


In [8]:
print(f'Initial array: {array}')
print(array[0:-1:2]) # the third element is the increment

Initial array: [1 2 3 4 5]
[1 3]


In [10]:
print(f'Initial array: {array}')
print(array[0::2]) # includes the last number ('5')
print(array[::2]) # includes the last number ('5')

Initial array: [1 2 3 4 5]
[1 3 5]
[1 3 5]


In [11]:
print(f'Initial array: {array}')
print(array[::])

Initial array: [1 2 3 4 5]
[1 2 3 4 5]


In [12]:
print(f'Initial array: {array}')
print(array[::-1])

Initial array: [1 2 3 4 5]
[5 4 3 2 1]
