# NumPy Getting Started Guide

NumPy, which stands for Numerical Python, is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, as well as mathematical functions for operations with these objects. It is also the basis of the Pandas library.



## Filters and np.where()

The `np.where()` function is very useful for making a conditional selection of elements from an array. For example, in a company, you may want to identify which employees have above-average salaries.


In [1]:
import numpy as np

# Salários dos funcionários
salaries = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

# Calcular a média salarial
mean_salaries = np.mean(salaries)

print(mean_salaries)

3714.285714285714


In [3]:
# Identify employees with above-average salaries

employees_above = np.where(salaries>mean_salaries)

print(employees_above)

(array([2, 4, 5, 6], dtype=int64),)


In [6]:
# to access the values
print(salaries[0]) 

# but you can also access with another array
print(salaries[employees_above])

# you can also do it directly
print(salaries[salaries>mean_salaries])

3000
[4000 4500 4000 5000]
[4000 4500 4000 5000]


In [9]:
print(np.where(salaries>mean_salaries,'above average','below average'))

['below average' 'below average' 'above average' 'below average'
 'above average' 'above average' 'above average']


In [10]:
# give 10% bonus to employees with below average salaries

employees_below = salaries[salaries<mean_salaries]
employees_below = employees_below* 1.1
print(employees_below)

# you can do this with where
employees_below = np.where(salaries<mean_salaries, salaries*1.1, salaries)
print(employees_below)

[3300. 3850. 2200.]
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]


In [12]:
# filter salaries between 3000 and 4500 with where

print(salaries[np.where((salaries>=3000) & (salaries<=4500))]) 


[3000 3500 4000 4500 4000]


In [17]:
# adjusted salaries

adj_salaries = np.where((salaries>=3000) & (salaries<=4500), salaries*1.05, salaries)

print(adj_salaries)

[3150. 3675. 4200. 2000. 4725. 4200. 5000.]


In [18]:
# filter salaries below 3000 or above 4500 with where

adj_salaries = np.where((adj_salaries < 3000) | (adj_salaries > 4500), adj_salaries*1.1, adj_salaries)
print(adj_salaries)

[3150.  3675.  4200.  2200.  5197.5 4200.  5500. ]
